Traceback (most recent call last):
  File "main.py", line 88, in <module>
    train_y_prob = model.predict_proba(train_x)[:, 1]
  File "/mnt/beegfs/home/jjohn273/git/HCPCS-Embeddings-For-Fraud-Detection/env/lib/python3.7/site-packages/xgboost/sklearn.py", line 933, in predict_proba
    missing=self.missing, nthread=self.n_jobs)
  File "/mnt/beegfs/home/jjohn273/git/HCPCS-Embeddings-For-Fraud-Detection/env/lib/python3.7/site-packages/xgboost/core.py", line 536, in __init__
    self._init_from_npy2d(data, missing, nthread)
  File "/mnt/beegfs/home/jjohn273/git/HCPCS-Embeddings-For-Fraud-Detection/env/lib/python3.7/site-packages/xgboost/core.py", line 612, in _init_from_npy2d
    data = np.array(mat.reshape(mat.size), copy=False, dtype=np.float32)
MemoryError: Unable to allocate 6.06 GiB for an array with shape (1627999593,) and data type float32
srun: error: node087: task 0: Exited with exit code 1
